CREATE TABLE IF NOT EXISTS SALIENCE_ENTITIES (
  ID text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  NAME text DEFAULT NULL,
  ENTITY_TYPE text DEFAULT NULL,
  SENTIMENT float DEFAULT NULL,
  CONFIDENCE float DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS SALIENCE_TOPICS (
  ID text NOT NULL,
  CREATED_AT timestamp DEFAULT NULL,
  NAME text DEFAULT NULL,
  HITS float DEFAULT NULL,
  SCORE float DEFAULT NULL
);
