CREATE TABLE TAG_LABELS (
  INTERACTION_ID VARCHAR(64) NOT NULL,
  INTERACTION_TYPE VARCHAR(64) NOT NULL,
  CREATED_AT datetime NOT NULL,
  NAMESPACE VARCHAR(255) NOT NULL,
  LABEL VARCHAR(255) NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
CREATE INDEX tag_labels_interaction_id_idx ON HASHTAGS (INTERACTION_ID);
CREATE INDEX tag_labels_interaction_type_idx ON HASHTAGS (INTERACTION_TYPE);
CREATE INDEX tag_labels_created_at_idx ON HASHTAGS (CREATED_AT);

CREATE TABLE TAG_SCORES (
  INTERACTION_ID VARCHAR(64) NOT NULL,
  INTERACTION_TYPE VARCHAR(64) NOT NULL,
  CREATED_AT datetime NOT NULL,
  NAMESPACE VARCHAR(255) NOT NULL,
  SCORE float NOT NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
CREATE INDEX tag_scores_interaction_id_idx ON TAG_SCORES (INTERACTION_ID);
CREATE INDEX tag_scores_interaction_type_idx ON TAG_SCORES (INTERACTION_TYPE);
CREATE INDEX tag_scores_created_at_idx ON TAG_SCORES (CREATED_AT);