CREATE TABLE IF NOT EXISTS INTERACTION (
  ID text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  CREATED_AT_UNIX INTEGER NOT NULL,
  USERNAME text DEFAULT NULL,
  IS_RETWEET SMALLINT DEFAULT NULL,
  TWITTER_LANG text DEFAULT NULL,
  FIRST_TAG text DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LINKS (
  ID text NOT NULL,
  CREATED_AT timestamp DEFAULT NULL,
  URL text DEFAULT NULL,
  TITLE text DEFAULT NULL,
  HOPS text[] DEFAULT NULL,
  DOMAIN text DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS RAW (
  ID text NOT NULL,
  SUBSCRIPTION_ID text NOT NULL,
  CSDL_HASH text NOT NULL,
  CSDL_HASH_TYPE text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  INTERACTION_TYPE text NOT NULL,
  DATA TEXT NOT NULL,
  PRIMARY KEY (ID,SUBSCRIPTION_ID)
);

CREATE TABLE IF NOT EXISTS SALIENCE_ENTITIES (
  ID text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  NAME text DEFAULT NULL,
  ENTITY_TYPE text DEFAULT NULL,
  SENTIMENT float DEFAULT NULL,
  CONFIDENCE float DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS SALIENCE_TOPICS (
  ID text NOT NULL,
  CREATED_AT timestamp DEFAULT NULL,
  NAME text DEFAULT NULL,
  HITS float DEFAULT NULL,
  SCORE float DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS INTERACTION_TAGS (
  ID text NOT NULL,
  CREATED_AT timestamp DEFAULT NULL,
  TAG_NAME text NOT NULL,
  TAG_VALUE_FLOAT float DEFAULT NULL,
  TAG_VALUE_ARRAY text DEFAULT NULL,
  PRIMARY KEY (ID,TAG_NAME)
);
