CREATE TABLE IF NOT EXISTS INTERACTION (
  ID text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  CREATED_AT_UNIX INTEGER NOT NULL,
  USERNAME text DEFAULT NULL,
  IS_RETWEET SMALLINT DEFAULT NULL,
  TWITTER_LANG text DEFAULT NULL,
  FIRST_TAG text DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RAW (
  ID text NOT NULL,
  SUBSCRIPTION_ID text NOT NULL,
  CSDL_HASH text NOT NULL,
  CSDL_HASH_TYPE text NOT NULL,
  CREATED_AT timestamp NOT NULL,
  INTERACTION_TYPE text NOT NULL,
  DATA TEXT NOT NULL,
  PRIMARY KEY (ID,SUBSCRIPTION_ID)
);

CREATE TABLE IF NOT EXISTS INTERACTION_TAGS (
  ID text NOT NULL,
  CREATED_AT timestamp DEFAULT NULL,
  TAG_NAME text NOT NULL,
  TAG_VALUE_FLOAT float DEFAULT NULL,
  TAG_VALUE_ARRAY text DEFAULT NULL,
  PRIMARY KEY (ID,TAG_NAME)
);


CREATE TABLE IF NOT EXISTS HASHTAGS (
  INTERACTION_ID text NOT NULL,
  INTERACTION_TYPE VARCHAR(64) NOT NULL,
  CREATED_AT datetime NOT NULL,
  HASHTAG VARCHAR(255) NULL
);
CREATE INDEX hashtags_interaction_id_idx ON HASHTAGS (INTERACTION_ID);
CREATE INDEX hashtags_interaction_type_idx ON HASHTAGS (INTERACTION_TYPE);
CREATE INDEX hashtags_created_at_idx ON HASHTAGS (CREATED_AT);

 
CREATE TABLE IF NOT EXISTS MENTIONS (
  INTERACTION_ID text NOT NULL,
  INTERACTION_TYPE VARCHAR(64) NOT NULL,
  CREATED_AT datetime NOT NULL,
  MENTION VARCHAR(255) NULL
);
CREATE INDEX mentions_interaction_id_idx ON MENTIONS (INTERACTION_ID);
CREATE INDEX mentions_interaction_type_idx ON MENTIONS (INTERACTION_TYPE);
CREATE INDEX mentions_created_at_idx ON MENTIONS (CREATED_AT);
